[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
aurthor = "hanlei<iownE9@163.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
